name: Build and Test

on:
    push:
        branches:
            - "*"
            - "*/*"
            - "**"
            - "!main"

    pull_request:
        branches:
            - main

jobs:
    buildAndTest:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Use Node.js v17.x
              uses: actions/setup-node@v3
              with:
                  node-version: 17.x
                  cache: "npm"

            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
