name: Build and Test

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!main"
      - "!develop"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js v17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  cypress-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js v17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
          cache: "npm"
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run dev
