name: Deploy Develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js v17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  cypress-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js v17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
          cache: "npm"

      - run: npm ci
      - run: npm run dev

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: buildAndTest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          docker_build_args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "orbital-minerva-develop"
          heroku_email: "e0726676@u.nus.edu"
